# ConfigMap Definition
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  APP_ENV: "production"
  APP_DEBUG: "false"

---

# Deployment Definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: my-config-map
